# Generated by Django 4.0.5 on 2022-06-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='added_by',
            new_name='added_by_user',
        ),
    ]
